play_motion:
  motions:
    hands_up:
      joints: [torso_2_joint, arm_right_6_joint, arm_right_5_joint, arm_left_5_joint,
        torso_1_joint, arm_left_4_joint, head_2_joint, arm_right_2_joint, arm_left_3_joint,
        head_1_joint, arm_right_7_joint, arm_right_3_joint, arm_right_4_joint, arm_right_1_joint,
        arm_left_1_joint, arm_left_2_joint]
      points:
      - positions: [0.0, 0.0, -0.5, -0.5, 0.0, 1.3, 0.34, 0.0, -1.6, 0.0, 0.0, -1.6,
          1.4, 1.2, 0.9, 0.2]
        time_from_start: 0.0
    hold_lady:
      joints: [arm_left_7_joint, torso_2_joint, arm_right_6_joint, arm_right_5_joint,
        arm_left_5_joint, arm_left_6_joint, torso_1_joint, arm_left_4_joint, head_2_joint,
        arm_right_2_joint, arm_left_3_joint, head_1_joint, arm_right_7_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_1_joint, arm_left_1_joint, arm_left_2_joint]
      points:
      - positions: [0.11964535727, -0.0192237098171, -1.2681119075, 1.48944895753,
          1.47837256588, -0.61148719652, 0.0137113833752, 1.86785569035, 0.0, 0.291085568367,
          0.273189889462, 0.0, -0.186894387367, 0.0328059426067, 0.924701196518, 0.413466402682,
          0.0, 0.577942709219]
        time_from_start: 0.0
    home:
      joints: [arm_left_7_joint, torso_2_joint, arm_right_6_joint, arm_right_5_joint,
        arm_left_5_joint, arm_left_6_joint, torso_1_joint, arm_left_4_joint, head_2_joint,
        arm_right_2_joint, arm_left_3_joint, head_1_joint, arm_right_7_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_1_joint, arm_left_1_joint, arm_left_2_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 0.0
    pose_t:
      joints: [arm_left_7_joint, torso_2_joint, arm_right_6_joint, arm_right_5_joint,
        arm_left_5_joint, arm_left_6_joint, torso_1_joint, arm_left_4_joint, head_2_joint,
        arm_right_2_joint, arm_left_3_joint, head_1_joint, arm_right_7_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_1_joint, arm_left_1_joint, arm_left_2_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.61845375085, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.63474829429]
        time_from_start: 0.0
    surrender:
      joints: [arm_left_7_joint, torso_2_joint, arm_right_6_joint, arm_right_5_joint,
        arm_left_5_joint, arm_left_6_joint, torso_1_joint, arm_left_4_joint, head_2_joint,
        arm_right_2_joint, arm_left_3_joint, head_1_joint, arm_right_7_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_1_joint, arm_left_1_joint, arm_left_2_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.5708, 0.0, 1.5708, 1.5708,
          0.0, 0.0, 1.5708, 1.5708, 0.0, 0.0, 1.5708]
        time_from_start: 0.0
